server:
  port: 8083

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://portal.giantstepcorp.com:5432/do?charSet=utf-8&prepareThreshold=1
    username: giantstep_admin
    password: 1qaz2wsx#

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true
          default_batch_fetch_size: 1000
      open-in-view: false

